config/routes.rb
Rails.application.routes.draw do

  # ACCUEIL
  get '/', to: 'home#index'

  # REGISTRATION
  get 'registration/new', to: 'registration#new'
  post 'registration/log', to: 'registration#log'

  # USER CREATION
  get '/user/new', to: 'users#new'
  post '/user/create', to: 'users#create'

  # WELCOME PAGE
  get '/user/moussaillon', to: 'users#user_welcome'

  # gossips
  get 'gossips/new', to: 'gossips#new'
  post 'gossips/create', to: 'gossips#create'
  get '/gossips/:gossip_id', to: 'gossips#gossips', as: 'gossips'

  # Likes
  get 'gossips/likes/create', to: 'likes#create'
  post 'gossips/likes/create', to: 'likes#create'
  get 'gossips/likes/destroy', to: 'likes#destroy'
  post 'gossips/likes/destroy', to: 'likes#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/gossip.rb
class Gossip < ApplicationRecord

  belongs_to :user, optional: true
  has_many :comments
  has_many :likes

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/user.rb
class User < ApplicationRecord

  has_many :gossips
  has_many :comments
  has_many :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    puts "...........SERVEUR : dans la méthode new du controller gossips"
    @gossip = Gossip.new
  end

  def create

    puts "...........SERVEUR : dans la méthode create du controller gossips"
    puts "...........SERVEUR : $user_log.id : #{$user_log.id}"
    puts "...........SERVEUR : $user_log.name : #{$user_log.name}"
    puts "...........SERVEUR : $user_log.email : #{$user_log.email}"

    gossip = Gossip.new
    gossip.content = params[:gossip][:content]
    gossip.user_id = $user_log.id
    gossip.save
    @gossip_id = gossip.id
    @gossip_content = gossip.content
  end

  def gossips
    @gossip_id = params[:gossip_id]
  	$gossip = Gossip.find(params[:gossip_id])
    @likes = Like.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @gossip_last = Gossip.last
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    like = Like.new
  end

  def create
    like = Like.new
    like.user_id = $user_log.id
    like.gossip_id = $gossip.id
    like.save
    redirect_to "/user/moussaillon"
  end

  def destroy
    likes = Like.all
    likes.each do |like|

      puts "...........SERVEUR : like.gossip.id : #{like.gossip.id}"
      puts "...........SERVEUR : $gossip.id : #{$gossip.id}"
      puts "...........SERVEUR : #{like.gossip.id == $gossip.id}"
      puts "...........SERVEUR : like.user.id : #{like.user.id}"
      puts "...........SERVEUR : $user_log.id : #{$user_log.id}"
      puts "...........SERVEUR : #{like.user.id == $user_log.id}"
      
      if like.gossip.id == $gossip.id && like.user.id == $user_log.id
        puts "...........SERVEUR : dans le if"
        id = like.id
        puts "...........SERVEUR : id du like à supprimer : #{id}"
        Like.all.find(id).delete
        break
      end
    end
    redirect_to "/user/moussaillon"
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

  def new
    $user_log = User.new
    @user_test = User.all.first
  end

  def log
    @users = User.all
    @log_test = false
    @users.each do |user|

      puts "...........SERVEUR : #{@log_test}"
      puts "...........SERVEUR : #{params[:user][:email]} == #{user.email} ?"

      if params[:user][:email] == user.email && params[:user][:password] == user.password
        puts "...........SERVEUR : identification ok"
        @log_test = true
        $user_log.id = user.id
        $user_log.name = user.name
        $user_log.email = user.email
        $user_log.password = user.password

        puts "...........SERVEUR : $user_log.id : #{$user_log.id}"
        puts "...........SERVEUR : $user_log.name : #{$user_log.name}"
        puts "...........SERVEUR : $user_log.email : #{$user_log.email}"

        break
      end
    end
    if @log_test == false
      puts "...........SERVEUR : échec identification"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    puts "...........SERVEUR : dans la méthode new du controller users"

    @user = User.new

    puts "...........SERVEUR : "
    puts "...........SERVEUR : params[:user] = #{params[:user]}"
    puts "...........SERVEUR : "
  end

  def create
    puts "...........SERVEUR : dans la méthode create du controller users"

    user = User.new

    puts "...........SERVEUR : "
    puts "...........SERVEUR : params = #{params}"
    puts "...........SERVEUR : "

    user.name = params[:user][:name]
    user.email = params[:user][:email]
    user.password = params[:user][:password]
    user.save
    @user_id = user.id
    @user_name = user.name
  end

  def user_welcome
    @user_name = params[:user_name]
    @gossips = Gossip.all
    @likes = Like.all
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gossips/create.html.erb
<p><b>Gossip n°<%= @gossip_id %> : "<%= @gossip_content %>" créé !</b></p>

<p><a href="/user/moussaillon">Revenir à ma user page</a></p>

app/views/gossips/gossips.html.erb
<br><br>
<h3>Gossip n°<%= @gossip_id %></h3>

<p>
	Date et heure de publication du gossip : <%= $gossip.updated_at %><br><br>
	<%= $gossip.user.name %> a dit : <br>
	"<%= $gossip.content %>".
</p>

<p><a href="/user/moussaillon"><button type="button" name="button">Retour</button></a></p>

<!-- Compteur de like et likers -->
	<% cptr_like = 0 %>
	<% likers = [] %>
	<% already_like = false %>

	<% @likes.each do |like| %>
		<% if like.gossip.id == $gossip.id %>
			<% cptr_like += 1 %>
			<% likers << like.user.name %>

			<!-- Est-ce que le user loggé a déjà liké le gossip ? -->
			<% if like.user.id == $user_log.id %>
				<% already_like = true %>
			<% end %>

		<% end %>
	<% end %>

<!-- Affichage singulier / pluriel -->
	<% if cptr_like == 0 %>
			Ce potin a été liké par <%= cptr_like %> utilisateur.
	<% elsif cptr_like == 1 %>
			Ce potin a été liké par <%= cptr_like %> utilisateur : <%= likers.join(", ") %>
	<% elsif %>
			Ce potin a été liké par <%= cptr_like %> utilisateurs : <%= likers.join(", ") %>
	<% end %>

<br><br>
<p>
<% if already_like == false%>
	<a href="likes/create"><button type="button" name="button">Liker</button></a>
<% else %>
	<a href="likes/destroy"><button type="button" name="button">Disliker</button></a>
<% end %>
</p>

app/views/gossips/new.html.erb
<p><u>Gossip creation</u></p>
<%= form_for @gossip, url: {action: "create"} do |f| %>
  <%= label_tag 'content:' %>
  <%= f.text_field :content %>
  <br><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/home/index.html.erb
<h1>Bienvenue sur The Gossip Project</h1>
<br><br>

<p>Tu veux découvrir les meilleurs potins de la toile ? Crée ton compte dès maintenant !</p>
<p><a href="/user/new"><button type="button" name="button">Sign up</button></a></p>

<br><br>

<p>Tu es déja inscrit ?</p>
<p><a href="/registration/new"><button type="button" name="button">Sign in</button></a></p>

<br><br><br><br>
<h1>Voici la liste des utilisateurs déjà enregistrés</h1>
<p>Tu vois les mots de passes comme ça tu peux tester le Sign In</p>
  <% @users.each do |user| %>
  	<%= user.name %> , <%= user.email %> , <%= user.password %><br>
  <% end %>

<br><br><br><br>
<h1>Voici le dernier Gossip créé</h1>
  <%= @gossip_last.content %> par <%= @gossip_last.user.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Network</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/user/new">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/registration/new">Sign in</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
          </li>
        </ul>
      </div>
    </nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<p><b>Utilisateur n°<%= @user_id %> : "<%= @user_name %>" créé !</b></p>

<br>

<p><a href="/registration/new"><button type="button" name="button">Sign in</button></a></p>

app/views/users/new.html.erb
<h1>Création d'un compte</h1>


<p>Entre tes infos</p><br>


  <%= form_for @user, url: {action: "create"} do |f| %>
    <%= label_tag 'name:' %>
    <%= f.text_field :name, placeholder: "Name" %>

<br>
    <%= label_tag 'email:' %>
    <%= f.text_field :email, placeholder: "Email"%>
<br>

    <%= label_tag 'password:' %>
    <%= f.text_field :password, placeholder: "Password" %>
<br>

    <%= f.submit "Submit" %>
  <% end %>

app/views/users/user_welcome.html.erb
<h1>Bonjour à toi, <%= $user_log.name %> ! Bienvenue sur le meilleur forum de commérage au monnnnnde !</h1>

<p><a href="/gossips/new"><button type="button" name="button">Créer gossip</button></a></p>

<p><b>Sans plus attendre, je te présente la liste des potins du moment :</b><br><br>

<% @gossips.each do |gossip| %>
	<%= gossip.user.name %> a dit : "<%= gossip.content %>"

<!-- Compteur de like et likers -->
	<% cptr_like = 0 %>
	<% likers = [] %>
	<% @likes.each do |like| %>
		<% if like.gossip.id == gossip.id %>
			<% cptr_like += 1 %>
			<% likers << like.user.name %>
		<% end %>
	<% end %>

<!-- Affichage singulier / pluriel -->
	<% if cptr_like == 0 %>
	- Ce potin a été liké par <%= cptr_like %> utilisateur.
	<% elsif cptr_like == 1 %>
	- Ce potin a été liké par <%= cptr_like %> utilisateur : <%= likers.join(", ") %>
	<% elsif %>
	- Ce potin a été liké par <%= cptr_like %> utilisateurs : <%= likers.join(", ") %>
	<% end %>

<!-- Lien vers page unique gossip -->
	<br>
	<%= link_to "> Clique ici pour afficher la page de ce potin <", gossips_path(gossip.id)%>

	<br><br>
<% end %>
</p>